apiVersion: v1
kind: Pod
metadata:
  name: naver-exporter-pod
  labels:
    app: naver-exporter
spec:
  containers:
    - name: naver-exporter-container
      image: whpark70/naver-health-exporter
      env:
        - name: HTTP_URL
          value: "https://naver.com"
        - name: CHECK_INTERVAL
          value: "5"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: metrics
          containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: naver-exporter-service
  labels:
    app: naver-exporter
spec:
  selector:
    app: naver-exporter
  ports:
    - port: 9000
      targetPort: 9000
      name: metrics
---

