## Provide a name in place of kube-prometheus-stack for `app:` labels
##
# nameOverride: "prometheus"

# ## Override the deployment namespace
# ##
# namespaceOverride: "prometheus"
# fullnameOverride: "prometheus"

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      {
        alb.ingress.kubernetes.io/scheme: "internet-facing",
        alb.ingress.kubernetes.io/target-type: "ip",
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]',
        alb.ingress.kubernetes.io/backend-protocol: "HTTP",
        alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
        alb.ingress.kubernetes.io/actions.ssl-redirect: "443",
        alb.ingress.kubernetes.io/success-codes: "200,302",
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:532805286864:certificate/67ededc5-c221-4e88-a3d4-20fc71efd82b",
        alb.ingress.kubernetes.io/group.name: "monitoring-alb-group",
      }

    Hosts:
      - grafana.steve-aws.com
    paths:
      - /