## Provide a name in place of kube-prometheus-stack for `app:` labels
##
# nameOverride: "prometheus"

# ## Override the deployment namespace
# ##
# namespaceOverride: "prometheus"
fullnameOverride: "kube-prometheus"

prometheus:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${thanos_sidecar_role_arn}

  thanosService:
    enabled: enable

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    thanos:
      image: quay.io/thanos/thanos:v0.29.0
      objectStorageConfig:
        name: ${thanos_sidecar_objconfig_secret_name}
        key: thanos.yaml

grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      {
        alb.ingress.kubernetes.io/scheme: "internet-facing",
        alb.ingress.kubernetes.io/target-type: "ip",
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]',
        alb.ingress.kubernetes.io/backend-protocol: "HTTP",
        alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
        alb.ingress.kubernetes.io/actions.ssl-redirect: "443",
        alb.ingress.kubernetes.io/success-codes: "200,302",
        alb.ingress.kubernetes.io/certificate-arn: ${certificate_arn},
        alb.ingress.kubernetes.io/group.name: "monitoring-alb-group",
      }

    hosts:
      - grafana.steve-aws.com
    paths:
      - /
