FROM python:alpine3.17 AS builder

ENV AWSCLI_VERSION=2.11.6

RUN apk add --no-cache \
    curl \
    make \
    cmake \
    gcc \
    g++ \
    libc-dev \
    libffi-dev \
    openssl-dev \
    && curl https://awscli.amazonaws.com/awscli-${AWSCLI_VERSION}.tar.gz | tar -xz \
    && cd awscli-${AWSCLI_VERSION} \
    && ./configure --prefix=/opt/aws-cli/ --with-download-deps \
    && make \
    && make install

FROM python:alpine3.17

RUN apk --no-cache add groff --update podman  fuse-overlayfs && apk add sudo yq
RUN sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf

RUN echo jenkins:1000:65536 >/etc/subuid
RUN echo jenkins:1000:65536 >/etc/subgid

COPY --from=builder /opt/aws-cli/ /opt/aws-cli/