apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
