apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/woohwan/docker-build-test.git"
        - "--destination=532805286864.dkr.ecr.ap-northeast-2.amazonaws.com/kaniko-demo:1.0"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      resources:
        limits:
          cpu: 1
          memory: 1Gi
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
data:
  config.json: |-
    { "credsStore": "ecr-login" }
