apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
        # when not using instance role
        - name: aws-secret
          mountPath: /root/.aws/
  restartPolicy: Never
  volumes:
    # when not using instance role
    - name: aws-secret
      secret:
        secretName: kaniko-secret
